services:
  backend:
    build: .
    container_name: mini-lib-backend
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    env_file:
      - .env

  mongodb:
    image: mongo:6
    container_name: mini-lib-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
