services:
  mongodb:
    image: mongo:6
    container_name: mini-lib-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: mini-lib-redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  mongo_data:
